# Generated by Django 5.2.12 on 2026-03-25 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('excel_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('excel_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('records_extracted', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.CharField(blank=True, max_length=20)),
                ('invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=50)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cess', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('return_period', models.CharField(blank=True, max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_corrected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='documents.uploadjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_data', models.JSONField()),
                ('original_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='documents.extractedrecord')),
            ],
        ),
    ]
